<!--?overlay-->
<div class="overlay faded hide-for-big-devices"></div>

<!--?navigation-->
<nav class="nav flex flex-jc-sb flex-ai-c">
    <!--*logo-Artemis-->
    <div class="nav__logo">
        <h2>ARTEMIS</h2>
    </div>

    <!--*menu-links-->
    <ul class="flex flex-jc-sb nav__menu hide-for-small-devices">
        <li><a href="#">Home</a></li>
        <li><a href="#gallery">Gallery</a></li>
        <li><a href="blog.html">Blog</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="contact.html">Contact</a></li>
         
        <!--sign In/Up links-->
        <li><a href="login" class="nav__menu--login">Log In</a></li>
        <button class="nav__menu--signup">Sign Up</button>
    </ul>


    <!--*hamburger-menu-->
    <div id="humburgerBtn" class="nav__hambergurMenu hide-for-big-devices">
        <span></span>
        <span></span>
        <span></span>
    </div>

</nav>

<!--****block-menu<-click the humbergerMenu**-->
<div class="faded header__blockMenu flex flex-fd-c hide-for-big-devices">
    <a href="#">Home</a>
    <a href="#gallery">Gallery</a>
    <a href="blog.html">Blog</a>
    <a href="#about">About</a>
    <a href="contact.html">Contact</a>

    <!--sign In/Up links-->
    <div class="sign flex flex-jc-c">
        <a href="login" class="sign--login">Log In</a>
        <button class="sign--signup">Sign Up</button>
    </div>
</div>

<!--?article-part-->
<!--*imgs part-->

<!--*writting part-->
        
