<!--?overlay-->
<div class="overlay faded hide-for-big-devices"></div>
 
 <!--?navigation-->
 <nav class="nav flex flex-jc-sb flex-ai-c bg-nav">
     <!--*logo-Artemis-->
     <div class="nav__logo">
         <h2>ARTEMIS</h2>
     </div>

     <!--*menu-links-->
     <ul class="flex flex-jc-sb nav__menu hide-for-small-devices">
         <li><a href="#" class="active">Home</a></li>
         <li><a href="gallery.html">Gallery</a></li>
         <li><a href="blog.html">Blog</a></li>
         <li><a href="about us.html">About</a></li>
         <li><a href="contact.html">Contact</a></li>
         
         <!--sign In/Up links-->
         <li><a href="log in.html" class="nav__menu--login">Log In</a></li>
         <button class="nav__menu--signup"><a href="sign up.html">Sign Up</a></button>
     </ul>


     <!--*hamburger-menu-->
     <div id="humburgerBtn" class="nav__hambergurMenu hide-for-big-devices">
         <span></span>
         <span></span>
         <span></span>
     </div>

 </nav>

 <!--****block-menu<-click the humbergerMenu**-->
<div class="faded header__blockMenu flex flex-fd-c hide-for-big-devices">
    <a href="index-g.html">Home</a>
    <a href="#" class="active">Gallery</a>
    <a href="blog.html">Blog</a>
    <a href="about.html">About</a>
    <a href="contact.html">Contact</a>

    <!--sign In/Up links-->
    <div class="sign flex flex-jc-c">
        <a href="login" class="sign--login">Log In</a>
        <button class="sign--signup">Sign Up</button>
    </div>
</div>